# Site settings
author: Derek P.
title: Software Engineering Blog
header-img: img/home-bg.png
email: dragevards@gmail.com
copyright_name: Derek P.
description: > # this means to ignore newlines until "baseurl:"
  Recaps
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  dragevard

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
